### ISSUE TITLE
Karsruhe and Munich

### ISSUE THREAD

**Issue by kirienko** [oscovida/oscovida#104]
@fangohr wrote:

> Halimah approach me to ask why we have two entries for Munich and two entries for Karlsruhe in our list at https://oscovida.github.io/germany-incidence-rate-14day-20cases.html
> 
> Halimah, thank you for pointing this out.
> 
> I am pretty certain that this is because one of them is a Landkreis (LK) and the other one is the Stadtkreis (SK). So SK Munich should be a subregion of LK Munich.
> 
> For the table on https://oscovida.github.io/germany-incidence-rate-14day-20cases.html, we have removed the SK and LK labels from the name of the region to allow alphabetic sorting by district name. But we hadn’t realised that this can cause confusion as you describe.
> 
> So, Halimah, I hope I have answered your question.
> 
> Robert, Yury, could you update the code to not remove the LK and SK labels, but to move them to the end of the district name? I.e. transfer “SK Hamburg” to become “Hamburg (SK)” ? I think that might be an easy solution to solve this.

**Comment by fangohr** [comment]
Thanks. There is at least one annoying exception: the region "Germany: Nordrhein-Westfalen : StadtRegion Aachen" has neither "SK" nor "LK" in the beginning. So the current command would scramble the region and chop off the first three letters of "Aachen". (https://oscovida.github.io/html/Germany-Nordrhein-Westfalen-StadtRegion-Aachen.html)

So I think we must check if the string starts with "LK", then move "(LK)" to the end. Same check and action for "SK". If neither of those is true, we should leave it as is (I think).

**Comment by kirienko** [comment]
Oh, sorry. I checked briefly by my eyes, but of course I missed that exception. Okay, I'll make this fix a bit bigger than one line :wink:

**Comment by kirienko** [comment]
Now it works properly.

**Comment by kirienko** [comment]
Fixed via #105
