### ISSUE TITLE
Fix missing links for the Germany incidence rate pages

### ISSUE THREAD

**Issue by RobertRosca** [oscovida/oscovida#125]
- [x] The locations do not have links
- [x] Maybe(?) add back in the state to the location

**Comment by fangohr** [comment]
Having thought about travelling in Germany, I think having the state attached to the string would be very useful after all. It allows checking what the situation is like in a larger area (the state). One way to do this could be to use a string like

`Pinneberg (LK), Schleswig-Holstein` : this way, we can sort alphabetically according to Kreis (as we can do now) but by typing 'Schleswig-Holstein' into the search box, you can filter for just the Kreise from the state.

**Comment by RobertRosca** [comment]
Closed by #128
