### ISSUE TITLE
other tutorials link is broken

### ISSUE THREAD

**Issue by daviddoji** [oscovida/oscovida#132]
When trying to acces other tutorials by going to https://oscovida.github.io/0-tutorial-index.ipynb, you get a "File not found" error.

**Comment by slel** [comment]
The correct link might be https://oscovida.github.io/tag-tutorial.html

**Comment by fangohr** [comment]
Thanks, @daviddoji - on which page (URL? Notebook in binder? ...) do you see the link to  https://oscovida.github.io/0-tutorial-index.ipynb ?

**Comment by daviddoji** [comment]
It's on the [https://oscovida.github.io/](oscovida.github.io) . If you navigate to the '**Articles**' tab and click on the '**Tutorial: Installing OSCOVIDA**' from 05 July, at the end of the opened page, under the '**Other tutorials**' subheading, there you can find the broken link.

**Comment by fangohr** [comment]
Thanks @daviddoji and @slel - this should be fixed now.
