### ISSUE TITLE
Bug: change in `get_country_data` behaviour?

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#135]
The notebook template is failing in cell [6] (see https://oscovida.github.io/html/Germany.html) and screenshot:
![Screenshot 2020-10-23 at 11 04 14](https://user-images.githubusercontent.com/4489119/96979774-81283f00-151f-11eb-816c-a99df65dcdd5.png)

**Comment by fangohr** [comment]
A change in behaviour would be fine I think - we just need to update the notebook template that uses it.

**Comment by fangohr** [comment]
Associated (I think), we need updates of https://oscovida.github.io/tutorial-accessing-cases-and-deaths.nbdata.html where the code has been updated but the narrative needs changes. I'd remove the following cells and the markdown explaining the Italy example:

![Screenshot 2020-10-23 at 11 20 27](https://user-images.githubusercontent.com/4489119/96986328-ca798e00-1521-11eb-8dcf-cee83df80b79.png)
![Screenshot 2020-10-23 at 11 20 08](https://user-images.githubusercontent.com/4489119/96986341-cea5ab80-1521-11eb-8fcb-d67bb9362bb4.png)

**Comment by kirienko** [comment]
You're right, the number of returned values has been changed. I thought I fixed all occurrences of this function call, but that one I missed. My bad. I will rework this one as well.

**Comment by fangohr** [comment]
Fixed the tutorial notebook in https://github.com/oscovida/oscovida/pull/136
