### ISSUE TITLE
Legends missing and in wrong place

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#137]
Taken from https://oscovida.github.io/html/Germany.html :

<img width="766" alt="Screenshot 2020-10-24 at 11 26 06" src="https://user-images.githubusercontent.com/4489119/97078303-bbf7a900-15eb-11eb-8d04-e910c02035ac.png">

(i) the legend for the doubling time (lowest plot) is missing

(ii) the legend for the daily new deaths is wrong (it reads doubling time). Seems to apply to all countries.

**Comment by kirienko** [comment]
Already fixed in #134
