### ISSUE TITLE
Normalise data per 100k population for international comparison plots

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#145]
The data shown in 
<img width="1171" alt="Screenshot 2020-10-25 at 21 15 33" src="https://user-images.githubusercontent.com/4489119/97117940-51d42680-1707-11eb-8a41-d4551df0af3f.png">
shows absolute numbers.

It would be more instructive if these were per 100k.

Source of bitmap: https://oscovida.github.io/html/France.html

**Comment by slel** [comment]
I would suggest "per million" rather than "per 100k".

**Comment by fangohr** [comment]
I'd like to stick to per 100k because that is used widely. (Although as a scientist I agree that 10^6 would be better than 10^5.)

**Comment by fangohr** [comment]
Discussion with Yury: switch our notebook template to show normalised data.
