### ISSUE TITLE
Update report notebooks in binder repo

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#161]
The notebooks in the binder repo (such as this one: https://github.com/oscovida/binder/blob/master/ipynb/Germany.ipynb) are not up-to-date with the ones in the main repository.

(The API change from `get_country_data` has not propagated here yet.)

So we need to (i) do this now and (ii) have a way of doing this automatically (or at least so that it can be triggered manually but then works automatically).

**Comment by RobertRosca** [comment]
Done in https://github.com/oscovida/binder/pull/3
