### ISSUE TITLE
Fix Marshall Islands failed test

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#164]
Just a few hours since we've just discussed the stability of a county set... And here comes a new country -- Marshall Islands!

https://travis-ci.com/github/oscovida/oscovida/jobs/417052177

**Comment by kirienko** [comment]
No longer reproducible, probably the two datasets were synchronized by their maintainers.

And according to Wikipedia, the Marshall Islands have more inhabitants than Liechtenstein or San-Marino.
