### ISSUE TITLE
Broken filename (tutorial-overview-plot_reporduction_number.ipynb)

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#190]
This file (tutorial-overview-plot_reporduction_number.ipynb) should probably be called tutorial-overview-plot_reproduction_number.ipynb (swap 'or' with 'ro').

The nbdata file as the 'correct' filename already.

```
(oscovida) > $ ls -1 tutorial-overview-plot_rep*                                                                               
tutorial-overview-plot_reporduction_number.ipynb
tutorial-overview-plot_reproduction_number.nbdata

(oscovida) > $ pwd                     
/Users/fangohr/git/oscovida/tools/pelican/content/ipynb
```

Pelican reports an error when coming across this.

**Comment by kirienko** [comment]
Closed via https://github.com/oscovida/oscovida/commit/66ed5d5e8821a9e7562c7ffab4a2be6c4c896741
