### ISSUE TITLE
Fix LK Aachen issue

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#194]
This is new as well: https://github.com/oscovida/oscovida/runs/1498418948?check_suite_focus=true#step:6:66

"LK Aachen" seems to be missing somewhere.

This is also already in the live system: https://oscovida.github.io/html/Germany-Nordrhein-Westfalen-LK-Aachen.html

Not sure what the cause here is. "LK Aachen" seems like a respectable district and district name.

**Comment by kirienko** [comment]
For some uncertain [for me personally] reason Aachen is now a `StadtRegion` and not a `LK`. I will fix that in the code.

**Comment by kirienko** [comment]
There are several changes that might be related:
* https://github.com/oscovida/oscovida/commit/05d91cd140c3e46feff523c27bf4d3a0c979d922
* https://github.com/oscovida/oscovida/commit/ad35b5c39f940f98e49d013858f47f405e951be3

**Comment by kirienko** [comment]
Okay, I don't know where does that link come from, but Aachen is not actually a `LandKreis` but a `StadtRegion`. And it is still on its place: https://oscovida.github.io/html/Germany-Nordrhein-Westfalen-StadtRegion-Aachen.html

The same stands for [Region Hannover](https://oscovida.github.io/html/Germany-Niedersachsen-Region-Hannover.html).

We can still reach the right destination from either the list of [German regions](https://oscovida.github.io/germany.html) or from the [incidence rate table](https://oscovida.github.io/germany-incidence-rate.html).

**Comment by fangohr** [comment]
> For some uncertain [for me personally] reason Aachen is now a `StadtRegion` and not a `LK`. I will fix that in the code.

I had Aachen down as a city rather than a region, so that would be consistent. 

I don't know what change we need to do (I am guessing syncing names in actual data and population?) - do we track the separately? (Just asking because you added the 'wont-fix' label below.)
