### ISSUE TITLE
LK Saarpfalz-Kreis Renamed

### ISSUE THREAD

**Issue by RobertRosca** [oscovida/oscovida#210]
There's an error causing the tests to fail:

```
E         Extra items in the left set:
E         'LK Saarpfalz-Kreis'
E         Extra items in the right set:
E         'LK Saar-Pfalz-Kreis'
```

Looks like this Landkreis was renamed which leads to a check failing.

_Originally posted by @RobertRosca in https://github.com/oscovida/oscovida/issues/209#issuecomment-769668803_

**Comment by kirienko** [comment]
Also [this page](https://oscovida.github.io/html/Germany-Saarland-LK-Saarpfalz-Kreis.html) is broken fro the same reason.
