### ISSUE TITLE
In cell [5] use new-ish function call for `compare_plot`

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#223]
- this is done already for German districts, but missing for JHU data
- new function call should be something: `compare_plot(..., dates="2020-03-15:")` (see any German district).

**Comment by kirienko** [comment]
We have quite a lot of code duplication there, and that's the reason we will have to either add even more duplicate code into the `make_compare_plot` function or refactor the whole set of similar functions into one.  Anyway, that's not a `small`, it requires to scatter more than, dunno, 20 non-trivial lines of code here and there.
