### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by kirienko** [oscovida/oscovida#225]
We need to update the documentation after we introduced the incidence rate plot:
* https://oscovida.github.io/tutorial-overview-graph.html
* https://oscovida.github.io/plots.html

**Comment by fangohr** [comment]
Hi Yury, do you want to have a go at this with a first draft, and I can go over the text afterwards? [I'd like to have the the documentation (and plot 1) updated before tweeting about the new features.]

**Comment by kirienko** [comment]
I think it's done, at least within the scope we intended.
