### ISSUE TITLE
US population numbers used for 7-d-i seems to be miscalculated

### ISSUE THREAD

**Issue by patrickg2525** [oscovida/oscovida#236]
The dataset listed as the source for US populations does not match the populations used for reporting. 

For example, the report for New York (https://oscovida.github.io/html/US-New-York.html) states the NY population as 39M, however the dataset being used (https://www.census.gov/data/datasets/time-series/demo/popest/2010s-counties-total.html#par_textimage_739801612) lists the NY population as 19M.

It looks like the dataset is being read incorrectly: In the New York example, the population dataset has the entire state's population on the top row (2019 = 19453561), followed by the populations for each county in the state (which would add up to the total). However, it looks like the total population row is being added along with each county's population, effectively doubling the population (which is why the report states the NY population as 38907122).

Therefore the 7-d-i and other calculations are half of what they should be.

I apologize if I'm misunderstanding the report where it states: 'Population of country="US", region="New York": 38907122 people'

**Comment by kirienko** [comment]
Thank you so much for the attentiveness! You're totally right! Indeed, we doubled the population of every US state. And no one had noticed that fact before. :see_no_evil: 

I fixed this issue in the #238, please have a look!

**Comment by patrickg2525** [comment]
Glad to help, even if a little bit. Thanks for the great work on this project! ;)
