### ISSUE TITLE
overview function [also] produces garbage

### ISSUE THREAD

**Issue by kirienko** [oscovida/oscovida#245]
With the latest update (#244, a newer version of `nbconvert`) we also got extra garbage from the `overview` function:

![image](https://user-images.githubusercontent.com/1487169/114597947-a3f70d00-9c91-11eb-892f-5e8ba4486121.png)

**Comment by kirienko** [comment]
This is reproducible locally with `nbconvert-6.0.7`

**Comment by fangohr** [comment]
Hm, how odd. And well spotted. What we see are the return values from the `overview` function. These should be suppressed because of the `;` at the end, but it seems they show up when using `nbconvert` in the new version.

**Comment by kirienko** [comment]
Seems to be a bug in the `jupyter-nbconvert`. Might be due to this change (introduced with the version `6.0.6`, therefore pinning to the `6.0.1` might be a valid fix): https://github.com/jupyter/nbconvert/pull/1411

**Comment by kirienko** [comment]
Looks good: https://oscovida.github.io/staging/246/html/Argentina.html

**Comment by fangohr** [comment]
This is resolved now.
