### ISSUE TITLE
FutureWarning for some countries 

### ISSUE THREAD

**Issue by kirienko** [oscovida/oscovida#251]
For some countries (e.g. UK, France, Netherlands) is a `FutureWarning`:

![Screenshot_20210706-092526_DuckDuckGo](https://user-images.githubusercontent.com/1487169/124553075-f719cf80-de3c-11eb-86ed-36720d604a3e.jpg)

**Comment by fangohr** [comment]
See https://github.com/oscovida/oscovida/blob/7786466836e8effb16ef1cbb91351e668128b45e/oscovida/oscovida.py#L147

**Comment by kirienko** [comment]
See the warning description here: https://pandas.pydata.org/docs/whatsnew/v1.3.0.html#deprecations

**Comment by kirienko** [comment]
Well, that quick and dirty fix (#253) does not really work. It does remove the warning but breaks other things.

**Comment by kirienko** [comment]
Isn't it fixed?

**Comment by fangohr** [comment]
I think it is. Thanks for pointing that out ;)
