### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#255]
Currently, tests are failing. We tend to notice this when we try to integrate changes, but should notice it when they start to fail.

Most test failures are from inconsistencies in the naming of regions/countries in the different data bases (JHU / population) or appearance of new / temporary districts in Germany.

We have scheduled the unit tests to run twice daily.

This ticket is to fix the code on master to make them pass again.

**Comment by kirienko** [comment]
It seems like it's fixed
