### ISSUE TITLE
page generation broken (21/08/21) - population data for German districts has disappeared from RKI pages

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#261]
Observation:
- webpages don't update as of the evening of 20/08/2021
- tests on my binder show: execution of US pages works
- execution of pages for districts in Germany seems to fail (for example the command `overview(country="Germany", subregion="SK Hamburg", weeks=5);`)
- a bit more digging shows that `germany_get_population()` fails. See details below.
- I would thus guess that the generation of pages for German districts is broken because we cannot retrieve the population numbers, and that the updating of the webpages is then not carried out for other countries either (although they seem to work when run manually using the `overview()` function).

Further details on the failure:
<pre>

d = germany_get_population()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-cfab9cc38c23> in <module>
----> 1 d = germany_get_population()

/srv/conda/envs/notebook/lib/python3.7/site-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    589 
    590     def __call__(self, *args, **kwargs):
--> 591         return self._cached_call(args, kwargs)[0]
    592 
    593     def __getstate__(self):

/srv/conda/envs/notebook/lib/python3.7/site-packages/joblib/memory.py in _cached_call(self, args, kwargs, shelving)
    532 
    533         if must_call:
--> 534             out, metadata = self.call(*args, **kwargs)
    535             if self.mmap_mode is not None:
    536                 # Memmap the output at the first call to be consistent with

/srv/conda/envs/notebook/lib/python3.7/site-packages/joblib/memory.py in call(self, *args, **kwargs)
    759         if self._verbose > 0:
    760             print(format_call(self.func, args, kwargs))
--> 761         output = self.func(*args, **kwargs)
    762         self.store_backend.dump_item(
    763             [func_id, args_id], output, verbose=self._verbose)

/srv/conda/envs/notebook/lib/python3.7/site-packages/oscovida/oscovida.py in germany_get_population()
    452     population = (
    453         population
--> 454         .set_index('county')
    455     )
    456     population = population.rename(columns={"EWZ": "population"})

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/core/frame.py in set_index(self, keys, drop, append, inplace, verify_integrity)
   4725 
   4726         if missing:
-> 4727             raise KeyError(f"None of {missing} are in the columns")
   4728 
   4729         if inplace:

KeyError: "None of ['county'] are in the columns"
</pre>

This function tries to download a css file from `rki_population_url` which is https://opendata.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0.csv

That file is meant to include the population numbers for German districts in a CSV file, but seems to have changed.

I would speculate that the same data is available elsewhere. If we find the file, it might be enough to change the `rki_population_url` in https://github.com/oscovida/oscovida/blob/master/oscovida/data_sources.py#L11 to fix this.

**Comment by fangohr** [comment]
I did a first search for the data source on the RKI pages (no success).

I did leave a question in this forum (https://www.arcgis.com/home/item.html?id=f10774f1c63e40168479a1feb6c7ca74), but we don't know if this is the right place to ask, and/or if the given URL allows to find the information of the new URL (if there is one). Worth a try though, I thought.

**Comment by fangohr** [comment]
I propose a fix by which we use the backup data that @kirienko kindly committed about a year ago :) if the online data is unavailable.

This makes the tests pass (run with `py.test`), and I can locally run the `oscovida.overview("Germany", subregion="LK Pinneberg")` command for German districts. 

We have now encountered a fail in the page generation tests. @RobertRosca - any ideas? It seems my new patching code is used
(see for example https://github.com/oscovida/oscovida/pull/262/checks?check_run_id=3392335437#step:10:1036) but that the actual backup data file is not found: 

https://github.com/oscovida/oscovida/pull/262/checks?check_run_id=3392335437#step:10:1023



 why this may be different code from what is tested with `py.test`? (https://github.com/oscovida/oscovida/pull/262/checks?check_run_id=3392335437)

**Comment by kirienko** [comment]
According to that forum @fangohr mentioned, it looks like we're not the only ones who noticed that 😉

**Comment by fangohr** [comment]
That has been fixed.
