### ISSUE TITLE
Bug: data error (`SK Eisenach`)

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#272]
Something has changed (presumably in theta) which leads to these fails for all Python versions:  https://github.com/oscovida/oscovida/actions/runs/1360598775

`SK Eisenach` seems to have disappeared from one set of data, but not another: https://github.com/oscovida/oscovida/runs/3943514094?check_suite_focus=true#step:6:128

At this point, it breaks our CI tests. Updating of the main site seems to carry on successfully.

**Comment by kirienko** [comment]
I think we can close this one.
