### ISSUE TITLE
Tests fail (missing Antarctica in population data)

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#288]
See https://github.com/oscovida/oscovida/actions/runs/1738529419

With actual error at https://github.com/oscovida/oscovida/runs/4918193873?check_suite_focus=true#step:6:335

At the moment, the error is hard to read (because we catch the assert that py.test would otherwise detail for us with the values on the left and right).

**Comment by kirienko** [comment]
I think it is solved.
