### ISSUE TITLE
rename coronavirus -> oscovida, put on PyPI

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#41]
- [x] Rename the current package name 'coronavirus' to 'oscovida'
- [x] update code and tests
- [x] update notebooks in dev, tools and notebooks 
- [ ] put on PyPI

**Comment by kirienko** [comment]
It'd be nice to have _a release_ in order to package. We can do the same from the latest master, that's not a problem technically, but an explicit version is better than a hash IMO.

**Comment by fangohr** [comment]
Sure. Shall we start with 0.1 for the current master?

**Comment by kirienko** [comment]
As you wish, any version number is good for me. But let's merge #58 first.
