### ISSUE TITLE
Bug in plotting comparison plots

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#55]
There are gaps in the lines (https://oscovida.github.io/html/Germany-Niedersachsen-LK-Leer.html).

![IMG_8762](https://user-images.githubusercontent.com/4489119/83539354-3453b580-a4f7-11ea-8bac-ede04926bf8c.jpg)

**Comment by fangohr** [comment]
We also have similar gaps in the data for Pinneberg:

https://oscovida.github.io/html/Germany-Schleswig-Holstein-LK-Pinneberg.html

![Uploading Screenshot 2020-11-04 at 21.11.40.png…]()

**Comment by kirienko** [comment]
:shrug:  Seem to be no longer reproducible, at least on the oscovida site pages. We might have changed something accidentally.
