### ISSUE TITLE
Normalise plots by total population

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#65]
For some comparisons it is useful to talk about the number of infections/deaths per million citizens rather than in absolute numbers. It would be nice to have that option.

**Comment by fangohr** [comment]
The COVID19 package provides population numbers: https://github.com/oscovida/oscovida/blob/master/dev/explore-COVID19Py.ipynb

**Comment by kirienko** [comment]
![image](https://user-images.githubusercontent.com/1487169/90069990-6cdfee80-dcf3-11ea-9f17-56f01f3fb5dc.png)

**Comment by kirienko** [comment]
Implemented in #94
