### ISSUE TITLE
Create framework for notebook that is executed everyday

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#91]
The idea is to host a (set/subdirectory of) notebook(s) somewhere in the repository, which is re-executed everyday when the html is re-computed. 

This could produce a table or plot that we want to update every day, for example a table of countries, ordered according to incidence.

This could also be used as a playground to explore new analysis before we accommodate this into our html/javascript tables from which countries are selected: it should be much easier to try this in a notebook. Or it could provide a permanent link and daily-updated source of information if the notebok is a good format.

An additional benefit is that if we include some analysis in the notebook that leads towards the table/plots, this can be parts of the tutorial that demo what can be done with oscovida.

Task for this issue: enable automatic processing of arbitrary notebooks with a trivial notebook as an example. First thing we could try as an example: compute the mortality rate as requested in issue #90.

**Comment by fangohr** [comment]
We could have just a config file with a list of paths to notebooks that are re-executed every time we update the webpages. I like the simplicity and clarity of that.

**Comment by fangohr** [comment]
This seems to be solved - @RobertRosca, can you add a line about where this is documented and/or which file to change to include more notebooks into this?

**Comment by RobertRosca** [comment]
Good idea! I have some documentation in the directory already [here](https://github.com/oscovida/oscovida/blob/master/tools/oscovida.github.io/readme.md) but there should be a reference to it in the info document or somewhere else as welll.
